export const SET_ARTICLES = 'ARTICLE/SET_ARTICLES';

export const NEXT_PAGE = 'ARTICLE/NEXT_PAGE';

export const PRE_PAGE = 'ARTICLE/PRE_PAGE';

export const SET_NOW_ARTICLE = 'ARTICLE/SET_NOW_ARTICLE';